package org.uu.dao.model;
// Generated 2012-5-12 22:26:37 by Hibernate Tools 3.2.1.GA



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private long adid;
     private String loginName;
     private String password;

    public Admin() {
    }

    public Admin(long adid, String loginName, String password) {
       this.adid = adid;
       this.loginName = loginName;
       this.password = password;
    }
   
    public long getAdid() {
        return this.adid;
    }
    
    public void setAdid(long adid) {
        this.adid = adid;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


