package org.uu.dao.model;
// Generated 2012-5-28 10:31:10 by Hibernate Tools 3.2.1.GA



/**
 * Avatar generated by hbm2java
 */
public class Avatar  implements java.io.Serializable {


     private Long avatarId;
     private Userinfo userinfo;
     private String url;

    public Avatar() {
    }

    public Avatar(Userinfo userinfo, String url) {
       this.userinfo = userinfo;
       this.url = url;
    }
   
    public Long getAvatarId() {
        return this.avatarId;
    }
    
    public void setAvatarId(Long avatarId) {
        this.avatarId = avatarId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


