package org.uu.dao.model;
// Generated 2012-5-25 13:01:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Blog generated by hbm2java
 */
public class Blog  implements java.io.Serializable {


     private Long blogId;
     private Userinfo userinfo;
     private String blogContent;
     private String blogType;
     private long viewCount;
     private long commentCount;
     private boolean visiable;
     private Date time;

    public Blog() {
    }

	
    public Blog(String blogContent, String blogType, long viewCount, long commentCount, boolean visiable, Date time) {
        this.blogContent = blogContent;
        this.blogType = blogType;
        this.viewCount = viewCount;
        this.commentCount = commentCount;
        this.visiable = visiable;
        this.time = time;
    }
    public Blog(Userinfo userinfo, String blogContent, String blogType, long viewCount, long commentCount, boolean visiable, Date time) {
       this.userinfo = userinfo;
       this.blogContent = blogContent;
       this.blogType = blogType;
       this.viewCount = viewCount;
       this.commentCount = commentCount;
       this.visiable = visiable;
       this.time = time;
    }
   
    public Long getBlogId() {
        return this.blogId;
    }
    
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getBlogContent() {
        return this.blogContent;
    }
    
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }
    public String getBlogType() {
        return this.blogType;
    }
    
    public void setBlogType(String blogType) {
        this.blogType = blogType;
    }
    public long getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(long viewCount) {
        this.viewCount = viewCount;
    }
    public long getCommentCount() {
        return this.commentCount;
    }
    
    public void setCommentCount(long commentCount) {
        this.commentCount = commentCount;
    }
    public boolean isVisiable() {
        return this.visiable;
    }
    
    public void setVisiable(boolean visiable) {
        this.visiable = visiable;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


