package org.uu.dao.model;
// Generated 2012-5-28 10:31:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BlogComment generated by hbm2java
 */
public class BlogComment  implements java.io.Serializable {


     private Long blogcommentId;
     private Blog blog;
     private Userinfo userinfo;
     private String content;
     private Date time;

    public BlogComment() {
    }

    public BlogComment(Blog blog, Userinfo userinfo, String content, Date time) {
       this.blog = blog;
       this.userinfo = userinfo;
       this.content = content;
       this.time = time;
    }
   
    public Long getBlogcommentId() {
        return this.blogcommentId;
    }
    
    public void setBlogcommentId(Long blogcommentId) {
        this.blogcommentId = blogcommentId;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


