package org.uu.dao.model;
// Generated 2012-5-25 13:01:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Feed generated by hbm2java
 */
public class Feed  implements java.io.Serializable {


     private Long feedId;
     private Userinfo userinfo;
     private String name;
     private long feedSrcid;
     private String feedType;
     private String title;
     private String description;
     private Date updateTime;

    public Feed() {
    }

	
    public Feed(Userinfo userinfo, String name, long feedSrcid, String feedType, String title, Date updateTime) {
        this.userinfo = userinfo;
        this.name = name;
        this.feedSrcid = feedSrcid;
        this.feedType = feedType;
        this.title = title;
        this.updateTime = updateTime;
    }
    public Feed(Userinfo userinfo, String name, long feedSrcid, String feedType, String title, String description, Date updateTime) {
       this.userinfo = userinfo;
       this.name = name;
       this.feedSrcid = feedSrcid;
       this.feedType = feedType;
       this.title = title;
       this.description = description;
       this.updateTime = updateTime;
    }
   
    public Long getFeedId() {
        return this.feedId;
    }
    
    public void setFeedId(Long feedId) {
        this.feedId = feedId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getFeedSrcid() {
        return this.feedSrcid;
    }
    
    public void setFeedSrcid(long feedSrcid) {
        this.feedSrcid = feedSrcid;
    }
    public String getFeedType() {
        return this.feedType;
    }
    
    public void setFeedType(String feedType) {
        this.feedType = feedType;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


