package org.uu.dao.model;
// Generated 2012-5-10 22:49:28 by Hibernate Tools 3.2.1.GA



/**
 * LoginInfo generated by hbm2java
 */
public class LoginInfo  implements java.io.Serializable {


     private long logininfoId;
     private Userinfo userinfo;
     private String password;
     private String loginName;

    public LoginInfo() {
    }

    public LoginInfo(long logininfoId, Userinfo userinfo, String password, String loginName) {
       this.logininfoId = logininfoId;
       this.userinfo = userinfo;
       this.password = password;
       this.loginName = loginName;
    }
   
    public long getLogininfoId() {
        return this.logininfoId;
    }
    
    public void setLogininfoId(long logininfoId) {
        this.logininfoId = logininfoId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }




}


