package org.uu.dao.model;
// Generated 2012-6-13 12:08:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PicComment generated by hbm2java
 */
public class PicComment  implements java.io.Serializable {


     private Long piccommentId;
     private Picture picture;
     private Userinfo userinfo;
     private String content;
     private Date time;

    public PicComment() {
    }

	
    public PicComment(Picture picture, Userinfo userinfo, Date time) {
        this.picture = picture;
        this.userinfo = userinfo;
        this.time = time;
    }
    public PicComment(Picture picture, Userinfo userinfo, String content, Date time) {
       this.picture = picture;
       this.userinfo = userinfo;
       this.content = content;
       this.time = time;
    }
   
    public Long getPiccommentId() {
        return this.piccommentId;
    }
    
    public void setPiccommentId(Long piccommentId) {
        this.piccommentId = piccommentId;
    }
    public Picture getPicture() {
        return this.picture;
    }
    
    public void setPicture(Picture picture) {
        this.picture = picture;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


