package org.uu.dao.model;
// Generated 2012-6-13 13:23:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Picture generated by hbm2java
 */
public class Picture  implements java.io.Serializable {


     private Long picId;
     private Userinfo userinfo;
     private String description;
     private Date time;
     private String picPath;

    public Picture() {
    }

	
    public Picture(Userinfo userinfo, Date time, String picPath) {
        this.userinfo = userinfo;
        this.time = time;
        this.picPath = picPath;
    }
    public Picture(Userinfo userinfo, String description, Date time, String picPath) {
       this.userinfo = userinfo;
       this.description = description;
       this.time = time;
       this.picPath = picPath;
    }
   
    public Long getPicId() {
        return this.picId;
    }
    
    public void setPicId(Long picId) {
        this.picId = picId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getPicPath() {
        return this.picPath;
    }
    
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }




}


