package org.uu.dao.model;
// Generated 2012-5-20 14:47:22 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Long statusId;
     private Userinfo userinfo;
     private String statusMessage;
     private Date time;
     private Set statusComments = new HashSet(0);

    public Status() {
    }

	
    public Status(Userinfo userinfo, String statusMessage, Date time) {
        this.userinfo = userinfo;
        this.statusMessage = statusMessage;
        this.time = time;
    }
    public Status(Userinfo userinfo, String statusMessage, Date time, Set statusComments) {
       this.userinfo = userinfo;
       this.statusMessage = statusMessage;
       this.time = time;
       this.statusComments = statusComments;
    }
   
    public Long getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Long statusId) {
        this.statusId = statusId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getStatusMessage() {
        return this.statusMessage;
    }
    
    public void setStatusMessage(String statusMessage) {
        this.statusMessage = statusMessage;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Set getStatusComments() {
        return this.statusComments;
    }
    
    public void setStatusComments(Set statusComments) {
        this.statusComments = statusComments;
    }




}


