package org.uu.dao.model;
// Generated 2012-5-20 14:47:22 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private Long uid;
     private String name;
     private boolean sex;
     private Date birthday;
     private String email;
     private String className;
     private Set blogs = new HashSet(0);
     private Set loginInfos = new HashSet(0);
     private Set feeds = new HashSet(0);
     private Set statusComments = new HashSet(0);
     private Set statuses = new HashSet(0);
     private Set blogComments = new HashSet(0);

    public Userinfo() {
    }

	
    public Userinfo(String name, boolean sex, Date birthday, String email, String className) {
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.email = email;
        this.className = className;
    }
    public Userinfo(String name, boolean sex, Date birthday, String email, String className, Set blogs, Set loginInfos, Set feeds, Set statusComments, Set statuses, Set blogComments) {
       this.name = name;
       this.sex = sex;
       this.birthday = birthday;
       this.email = email;
       this.className = className;
       this.blogs = blogs;
       this.loginInfos = loginInfos;
       this.feeds = feeds;
       this.statusComments = statusComments;
       this.statuses = statuses;
       this.blogComments = blogComments;
    }
   
    public Long getUid() {
        return this.uid;
    }
    
    public void setUid(Long uid) {
        this.uid = uid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isSex() {
        return this.sex;
    }
    
    public void setSex(boolean sex) {
        this.sex = sex;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Set getBlogs() {
        return this.blogs;
    }
    
    public void setBlogs(Set blogs) {
        this.blogs = blogs;
    }
    public Set getLoginInfos() {
        return this.loginInfos;
    }
    
    public void setLoginInfos(Set loginInfos) {
        this.loginInfos = loginInfos;
    }
    public Set getFeeds() {
        return this.feeds;
    }
    
    public void setFeeds(Set feeds) {
        this.feeds = feeds;
    }
    public Set getStatusComments() {
        return this.statusComments;
    }
    
    public void setStatusComments(Set statusComments) {
        this.statusComments = statusComments;
    }
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }
    public Set getBlogComments() {
        return this.blogComments;
    }
    
    public void setBlogComments(Set blogComments) {
        this.blogComments = blogComments;
    }




}


