package org.uu.dao.model;
// Generated 2012-6-4 1:31:02 by Hibernate Tools 3.2.1.GA



/**
 * Userrelation generated by hbm2java
 */
public class Userrelation  implements java.io.Serializable {


     private UserrelationId id;

    public Userrelation() {
    }

    public Userrelation(UserrelationId id) {
       this.id = id;
    }
   
    public UserrelationId getId() {
        return this.id;
    }
    
    public void setId(UserrelationId id) {
        this.id = id;
    }




}


