package org.uu.dao.model;
// Generated 2012-5-15 22:21:17 by Hibernate Tools 3.2.1.GA



/**
 * UserrelationId generated by hbm2java
 */
public class UserrelationId  implements java.io.Serializable {


     private long uid1;
     private long uid2;

    public UserrelationId() {
    }

    public UserrelationId(long uid1, long uid2) {
       this.uid1 = uid1;
       this.uid2 = uid2;
    }
   
    public long getUid1() {
        return this.uid1;
    }
    
    public void setUid1(long uid1) {
        this.uid1 = uid1;
    }
    public long getUid2() {
        return this.uid2;
    }
    
    public void setUid2(long uid2) {
        this.uid2 = uid2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserrelationId) ) return false;
		 UserrelationId castOther = ( UserrelationId ) other; 
         
		 return (this.getUid1()==castOther.getUid1())
 && (this.getUid2()==castOther.getUid2());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUid1();
         result = 37 * result + (int) this.getUid2();
         return result;
   }   


}


