package org.uu.dao.model;
// Generated 2012-5-28 10:31:10 by Hibernate Tools 3.2.1.GA



/**
 * Userrelation generated by hbm2java
 */
public class Userrelation  implements java.io.Serializable {


     private long uid2;
     private Userinfo userinfo;

    public Userrelation() {
    }

    public Userrelation(long uid2, Userinfo userinfo) {
       this.uid2 = uid2;
       this.userinfo = userinfo;
    }
   
    public long getUid2() {
        return this.uid2;
    }
    
    public void setUid2(long uid2) {
        this.uid2 = uid2;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }




}


