package org.uu.dao.model;
// Generated 2012-6-13 13:23:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private Long uid;
     private String name;
     private boolean sex;
     private Date birthday;
     private String email;
     private String className;
     private String avatar;
     private Set pictures = new HashSet(0);

    public Userinfo() {
    }

	
    public Userinfo(String name, boolean sex, Date birthday, String email, String className, String avatar) {
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.email = email;
        this.className = className;
        this.avatar = avatar;
    }
    public Userinfo(String name, boolean sex, Date birthday, String email, String className, String avatar, Set pictures) {
       this.name = name;
       this.sex = sex;
       this.birthday = birthday;
       this.email = email;
       this.className = className;
       this.avatar = avatar;
       this.pictures = pictures;
    }
   
    public Long getUid() {
        return this.uid;
    }
    
    public void setUid(Long uid) {
        this.uid = uid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isSex() {
        return this.sex;
    }
    
    public void setSex(boolean sex) {
        this.sex = sex;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Set getPictures() {
        return this.pictures;
    }
    
    public void setPictures(Set pictures) {
        this.pictures = pictures;
    }




}


